// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaspberryPuppyVs2.Data.EFDbContext;

#nullable disable

namespace RaspberryPuppyVs2.Migrations
{
    [DbContext(typeof(PuppyDbContext))]
    partial class PuppyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaspberryPuppyVs2.Models.Personality", b =>
                {
                    b.Property<int>("TagNr")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagNr");

                    b.ToTable("Personalities");
                });

            modelBuilder.Entity("RaspberryPuppyVs2.Models.TripData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TagNr")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("TimeOutside")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagNr");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RaspberryPuppyVs2.Models.TripData", b =>
                {
                    b.HasOne("RaspberryPuppyVs2.Models.Personality", "Personality")
                        .WithMany()
                        .HasForeignKey("TagNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");
                });
#pragma warning restore 612, 618
        }
    }
}
